### ISSUE TITLE
scalability & added services 

### ISSUE THREAD

**Issue by OmarHallab** [uffebjorklund/TI-CC2650#2]
Hi Uffe Björklund,

Wonderful IoT project!  i will implement it for a PoC soon :+1: 

Just a few Questions on my mind: 
1. Is the app scalable?  I see you did not predefine any UUID or mac ID for the sensortags .. how to connect to multiple sensortags? 
2. I want to integrate humidity & Temperature services that are also available on the sensortags, is it possible using Gatt services to add those to the project as well ? 

Thank you 
Omar 
:)

**Comment by uffebjorklund** [comment]
Hi @OmarHallab 

Happy that you like it :) I will try to update it to all the latest versions a.s.a.p since it is a year old now.
I'll try to answer your questions below.
1. The SensorTag lib can handle multiple sensortags https://github.com/sandeepmistry/node-sensortag
2. Yes you can use all the services available on the sensortag. I only used one in the project to avoid to much complexity.

Regards, Uffe

**Comment by OmarHallab** [comment]
Hi again @uffebjorklund,

That is Excellent news :) there are several Azure API's which will add a nice touch to the IoT project , Features I will be working on: 
1. Azure event hub & stream analytic services for real time streaming data + Analytic.
2. Power BI for real time streaming visualization.
3. Alert system if temperature or humidity surpasses certain thresholds (via sms, phone call, or email).

Thanks,
Omar
